# Generated by Django 5.1.6 on 2025-06-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('is_home', models.BooleanField(default=True)),
                ('season', models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], max_length=20)),
                ('competition_type', models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League')], default='Local Friendly', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
