# Generated by Django 5.2.1 on 2025-06-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.CharField(choices=[('U20', 'Under 20'), ('U17', 'Under 17'), ('U15', 'Under 15')], default='U20', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default='Azam Complex', max_length=100),
        ),
    ]
