# Generated by Django 5.2.1 on 2025-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When the match ended (UTC).', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When the match actually started (UTC).', null=True),
        ),
    ]
