# Generated by Django 5.2.1 on 2025-08-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0002_match_end_time_match_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=20),
        ),
    ]
