# Generated by Django 5.2.1 on 2025-06-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0003_playermatchstats_catches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='fouls_conceded',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='fouls_won',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='long_pass_success',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='pass_success_rate',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='red_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='total_passes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='yellow_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
