# Generated by Django 5.2.1 on 2025-09-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0003_alter_match_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_red_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_yellow_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
