# Generated by Django 5.2.1 on 2025-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0004_playermatchstats_fouls_conceded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logo/'),
        ),
        migrations.AddField(
            model_name='match',
            name='our_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logo'),
        ),
    ]
