# Generated by Django 5.2.1 on 2025-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0005_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('AZAM COMPLEX', 'AZAM COMPLEX'), ('NDC STADIUM', 'NDC STADIUM')], default='AZAM COMPLEX', max_length=50),
        ),
    ]
