# Generated by Django 5.2.1 on 2025-07-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0005_match_opponent_logo_match_our_team_logo'),
        ('players_app', '0007_alter_player_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchstats',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='goals',
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('is_own_goal', models.BooleanField(default=False)),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_made', to='players_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches_app.match')),
                ('scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_scored', to='players_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_score', models.PositiveIntegerField()),
                ('opponent_score', models.PositiveIntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
            ],
        ),
    ]
