# Generated by Django 5.2.1 on 2025-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0006_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League'), ('NBC Premier League', 'NBC Premier League'), ('CAF Confederation Cup', 'CAF Confederation Cup')], max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('AZAM COMPLEX', 'AZAM COMPLEX'), ('NDC STADIUM', 'NDC STADIUM'), ('MAJALIWA', 'MAJALIWA')], default='AZAM COMPLEX', max_length=50),
        ),
    ]
