# Generated by Django 5.2.1 on 2025-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0006_remove_playermatchstats_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
    ]
