# Generated by Django 4.0.6 on 2025-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0007_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League'), ('NBC Premier League', 'NBC Premier League')], max_length=50),
        ),
    ]
