# Generated by Django 5.2.1 on 2025-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0007_playermatchstats_is_starting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.CharField(choices=[('U20', 'Under 20'), ('U17', 'Under 17'), ('U15', 'Under 15'), ('U13', 'Under 13')], default='U20', max_length=10),
        ),
    ]
