# Generated by Django 4.0.6 on 2025-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0008_alter_match_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League'), ('NBC Premier League', 'NBC Premier League'), ('CAF Confederation Cup', 'CAF Confederation Cup')], max_length=50),
        ),
    ]
