# Generated by Django 5.2.1 on 2025-07-24 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0008_alter_match_season_alter_match_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchstats',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='clean_sheets',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='clearances',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='drops',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='fouls_conceded',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='fouls_won',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='is_goalkeeper',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='long_pass_success',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='pass_success_rate',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='penalties_saved',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='punches',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='saves_success_rate',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='total_passes',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='yellow_cards',
        ),
    ]
