# Generated by Django 5.2.1 on 2025-11-15 01:14

import django.db.models.deletion
from django.db import migrations, models


def clear_old_venue_values(apps, schema_editor):
    """Clear old text venue values before converting to FK."""
    Match = apps.get_model('matches_app', 'Match')
    Match.objects.update(venue=None)


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0008_alter_match_venue'),
    ]

    operations = [

        # STEP 1 — Make venue nullable FIRST to prevent NOT NULL errors
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),

        # STEP 2 — Clear old text values now that NULL is allowed
        migrations.RunPython(clear_old_venue_values),

        # STEP 3 — Create Region
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),

        # STEP 4 — Create Venue
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='matches_app.region')),
            ],
        ),

        # STEP 5 — Finally convert the field into the ForeignKey
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='matches_app.venue'),
        ),
    ]
