# Generated by Django 5.2.1 on 2025-07-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0009_remove_playermatchstats_catches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='formation',
            field=models.CharField(blank=True, choices=[('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-4-2', '4-4-2'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB1', 'Center Back 1'), ('CB2', 'Center Back 2'), ('CB3', 'Center Back 3'), ('RWB', 'Right Wing Back'), ('LWB', 'Left Wing Back'), ('CM1', 'Center Midfield 1'), ('CM2', 'Center Midfield 2'), ('CDM', 'Defensive Midfield'), ('CAM', 'Attacking Midfield'), ('RM', 'Right Midfield'), ('LM', 'Left Midfield'), ('RW', 'Right Wing'), ('LW', 'Left Wing'), ('ST', 'Striker'), ('ST1', 'Striker 1'), ('ST2', 'Striker 2')], help_text='Position in formation (used for pitch layout)', max_length=10, null=True),
        ),
    ]
