# Generated by Django 5.2.1 on 2025-07-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0010_match_formation_playermatchstats_position'),
        ('teams_app', '0006_agegroup_alter_staffmember_age_group_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='our_team_logo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams_app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams_app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League')], max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
