# Generated by Django 4.0.6 on 2025-11-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0010_merge_20251111_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('AZAM COMPLEX', 'AZAM COMPLEX'), ('NDC STADIUM', 'NDC STADIUM'), ('MAJALIWA', 'MAJALIWA'), ('MKWAKWANI STADIUM', 'MKWAKWANI STADIUM')], default='AZAM COMPLEX', max_length=50),
        ),
    ]
