# Generated by Django 5.2.1 on 2025-07-30 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0011_remove_match_formation_remove_match_is_home_and_more'),
        ('players_app', '0014_player_is_active'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playermatchstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playermatchstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teammatchresult',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams_app.agegroup'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams_app.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams_app.team'),
        ),
        migrations.CreateModel(
            name='AttemptToGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('body_part', models.CharField(choices=[('Left Foot', 'Left Foot'), ('Right Foot', 'Right Foot'), ('Head', 'Head'), ('Other', 'Other')], max_length=20)),
                ('delivery_type', models.CharField(choices=[('Pass', 'Pass'), ('Cross', 'Cross'), ('Loose Ball', 'Loose Ball'), ('Corner', 'Corner')], max_length=20)),
                ('shot_type', models.CharField(choices=[('Open Play', 'Open Play'), ('Counter Attack', 'Counter Attack'), ('Penalty', 'Penalty'), ('Set Piece', 'Set Piece'), ('Free Kick', 'Free Kick')], max_length=50)),
                ('outcome', models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error')], max_length=30)),
                ('x', models.DecimalField(decimal_places=2, help_text='X position on pitch (0–100)', max_digits=5)),
                ('y', models.DecimalField(decimal_places=2, help_text='Y position on pitch (0–100)', max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='players_app.player')),
                ('pre_assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assists', to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='PassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('x_start', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y_start', models.DecimalField(decimal_places=2, max_digits=5)),
                ('x_end', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y_end', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_successful', models.BooleanField(default=True)),
                ('is_possession_regained', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='players_app.player')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_from', to='teams_app.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_received', to='players_app.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_to', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('time_in', models.PositiveIntegerField(blank=True, null=True)),
                ('time_out', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_in', to='players_app.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_out', to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='PlayerMatchStats',
        ),
        migrations.DeleteModel(
            name='TeamMatchResult',
        ),
    ]
