# Generated by Django 5.2.1 on 2025-07-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0012_alter_playermatchstats_unique_together_and_more'),
        ('players_app', '0014_player_is_active'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerMatchAssignment',
            new_name='MatchLineup',
        ),
    ]
