# Generated by Django 4.0.6 on 2025-11-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0009_region_venue_alter_match_venue'),
        ('matches_app', '0012_merge_0008_alter_match_venue_0011_alter_match_venue'),
    ]

    operations = [
    ]
