# Generated by Django 4.0.6 on 2025-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0013_merge_20251115_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rating_links_sent',
            field=models.BooleanField(default=False),
        ),
    ]
