# Generated by Django 5.2.1 on 2025-07-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0013_rename_playermatchassignment_matchlineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchlineup',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='matchlineup',
            name='time_out',
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='time_entered',
            field=models.TimeField(blank=True, help_text='Time the player entered the field (for subs)', null=True),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('SUB', 'Substitute')], default='SUB', max_length=5),
        ),
    ]
