# Generated by Django 4.0.6 on 2025-11-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0010_match_rating_links_sent'),
        ('matches_app', '0014_match_rating_links_sent'),
    ]

    operations = [
    ]
