# Generated by Django 5.2.1 on 2025-07-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0014_remove_matchlineup_time_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passevent',
            name='from_player',
        ),
        migrations.RemoveField(
            model_name='passevent',
            name='from_team',
        ),
        migrations.RemoveField(
            model_name='passevent',
            name='match',
        ),
        migrations.RemoveField(
            model_name='passevent',
            name='to_player',
        ),
        migrations.RemoveField(
            model_name='passevent',
            name='to_team',
        ),
        migrations.DeleteModel(
            name='AttemptToGoal',
        ),
        migrations.DeleteModel(
            name='PassEvent',
        ),
    ]
