# Generated by Django 4.0.6 on 2025-11-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0015_merge_20251122_0521'),
        ('matches_app', '0015_merge_20251124_0938'),
    ]

    operations = [
    ]
