# Generated by Django 5.2.1 on 2025-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0015_remove_passevent_from_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('CHAMAZI COMPLEX', 'CHAMAZI COMPLEX')], default='CHAMAZI COMPLEX', max_length=50),
        ),
    ]
