# Generated by Django 5.2.1 on 2025-08-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0016_alter_match_venue'),
        ('players_app', '0014_player_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchlineup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='pod_number',
            field=models.CharField(blank=True, help_text='GPS Pod number assigned to the player in this match', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchlineup',
            unique_together={('match', 'player', 'pod_number')},
        ),
    ]
