# Generated by Django 5.2.1 on 2025-08-08 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0017_alter_matchlineup_unique_together_and_more'),
        ('players_app', '0014_player_is_active'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches_app.match'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players_app.player'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('SUB', 'Substitute')], default='SUB', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams_app.team'),
        ),
    ]
