# Generated by Django 4.0.6 on 2026-01-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0017_alter_match_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League'), ('NBC Premier League', 'NBC Premier League'), ('CAF Confederation Cup', 'CAF Confederation Cup'), ('Azam International Talent Showcase', 'Azam International Talent Showcase'), ('NMB Mapinduzi Cup', 'NMB Mapinduzi Cup')], max_length=50),
        ),
    ]
