# Generated by Django 5.2.1 on 2026-01-13 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0018_alter_match_competition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='matches_app.country'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'country')},
        ),
    ]
