# Generated by Django 5.2.1 on 2025-08-12 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0018_alter_matchlineup_match_alter_matchlineup_player_and_more'),
        ('players_app', '0014_player_is_active'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchlineup',
            options={'ordering': ['order', 'player__name']},
        ),
        migrations.RemoveField(
            model_name='matchlineup',
            name='time_entered',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='second',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='team',
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='minutes_played',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total minutes this player played in the match; calculated after substitutions or when the match ends.'),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional ordering key to control display order on UI.', null=True),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='time_in',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minute the player entered the match (e.g. 0 for starting XI or 1). Null = not yet played.', null=True),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='time_out',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minute the player went out of the match. Null = still on pitch or not used.', null=True),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='substitution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='is_starting',
            field=models.BooleanField(default=False, help_text='True if this player is in the starting eleven'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Match this player is registered for', null=True, on_delete=django.db.models.deletion.CASCADE, to='matches_app.match'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Player registered for this match', null=True, on_delete=django.db.models.deletion.CASCADE, to='players_app.player'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this player belongs to (optional if you derive from Player)', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams_app.team'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='match',
            field=models.ForeignKey(help_text='Match where substitution happened', on_delete=django.db.models.deletion.CASCADE, to='matches_app.match'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='minute',
            field=models.PositiveSmallIntegerField(help_text='Minute when the substitution occurred'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='player_in',
            field=models.ForeignKey(help_text='Lineup row for the player who came on', on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='matches_app.matchlineup'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='player_out',
            field=models.ForeignKey(help_text='Lineup row for the player who left the pitch', on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to='matches_app.matchlineup'),
        ),
    ]
