# Generated by Django 5.2.1 on 2026-01-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0019_country_alter_region_name_region_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
    ]
