# Generated by Django 5.2.1 on 2025-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0019_alter_matchlineup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
