# Generated by Django 5.2.1 on 2025-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0020_alter_matchlineup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='pod_number',
            field=models.CharField(blank=True, default='Demo', help_text='GPS Pod number assigned to the player in this match', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('RCB', 'Right Center Back'), ('LCB', 'Left Center Back'), ('LB', 'Left Back'), ('RM', 'Right Midfielder'), ('CM', 'Central Midfielder'), ('LM', 'Left Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('ST', 'Striker'), ('SUB', 'Substitute')], default='SUB', max_length=5, null=True),
        ),
    ]
