# Generated by Django 5.2.1 on 2025-08-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('HEAD_COACH', 'Head Coach'), ('ASSISTANT_COACH', 'Assistant Coach'), ('GOALKEEPER_COACH', 'Goalkeeper Coach'), ('FITNESS_COACH', 'Fitness Coach'), ('PHYSIO', 'Physiotherapist'), ('ANALYST', 'Performance Analyst'), ('TEAM_MANAGER', 'Team Manager'), ('PSYCHOLOGIST', 'Psychologist'), ('MEDIA_TEAM', 'Media Team'), ('OTHER', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('bio', models.TextField(blank=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams_app.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('team_type', models.CharField(choices=[('OUR_TEAM', 'Our Team'), ('OPPONENT', 'Opponent Team')], default='OUR_TEAM', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams_app.agegroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'age_group'), name='unique_team_per_age_group')],
            },
        ),
    ]
