# Generated by Django 5.2.1 on 2025-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams_app', '0002_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('HEAD_COACH', 'Head Coach'), ('ASSISTANT_COACH', 'Assistant Coach'), ('GOALKEEPER_COACH', 'Goalkeeper Coach'), ('FITNESS_COACH', 'Fitness Coach'), ('PHYSIO', 'Physiotherapist'), ('ANALYST', 'Performance Analyst'), ('TEAM_MANAGER', 'Team Manager'), ('PSYCHOLOGIST', 'Psychologist'), ('MEDIA_TEAM', 'Media Team'), ('OTHER', 'Other')], max_length=20)),
                ('age_group', models.CharField(choices=[('U20', 'Under 20'), ('U17', 'Under 17'), ('U15', 'Under 15'), ('U13', 'Under 13')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
