# Generated by Django 5.2.1 on 2025-07-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0006_agegroup_alter_staffmember_age_group_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'age_group'), name='unique_team_per_age_group'),
        ),
    ]
