# Generated by Django 4.0.6 on 2025-09-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches_app', '0001_initial'),
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacking', models.IntegerField(blank=True, null=True)),
                ('creativity', models.IntegerField(blank=True, null=True)),
                ('defending', models.IntegerField(blank=True, null=True)),
                ('tactical', models.IntegerField(blank=True, null=True)),
                ('technical', models.IntegerField(blank=True, null=True)),
                ('is_computed', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
