# Generated by Django 5.2.12 on 2026-04-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_app', '0009_player_status'),
        ('teams_app', '0005_country_team_country_region_team_region_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(choices=[('Forward', 'Forward'), ('Winger', 'Winger'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('FB', 'Full Back'), ('WB', 'Wing Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('WM', 'Wide Midfielder'), ('W', 'Winger'), ('ST', 'Striker')], max_length=10, null=True)),
                ('preferred_foot', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=10)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loaned_players/photos/')),
                ('loan_start_date', models.DateField()),
                ('loan_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_players_v2', to='teams_app.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='players_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('training', 'Training'), ('match', 'Match')], max_length=10)),
                ('training_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_type', models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly'), ('international', 'International'), ('tournament', 'Tournament')], max_length=20, null=True)),
                ('competition_name', models.CharField(blank=True, max_length=50, null=True)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True)),
                ('appearance', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('minutes_played', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('pre_assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_away_matches', to='teams_app.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_home_matches', to='teams_app.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='loans_app_v2.loanedplayer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
