# Generated by Django 5.2.1 on 2026-01-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_app', '0004_alter_matchlineup_position'),
        ('tagging_app_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passevent_v2',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_events_as_target', to='lineup_app.matchlineup'),
        ),
        migrations.AlterField(
            model_name='passevent_v2',
            name='action_type',
            field=models.CharField(choices=[('SHORT_PASS', 'Short Pass'), ('LONG_PASS', 'Long Pass'), ('GOAL_KICK', 'Goal Kick'), ('CLEARANCE', 'Clearance'), ('CROSS', 'Cross'), ('THROW_IN', 'Throw In'), ('LONG_THROW_IN', 'Long Throw In'), ('DRIBBLE', 'Dribble'), ('BALL_SHIELDING', 'Ball Shielding')], max_length=30),
        ),
        migrations.AlterField(
            model_name='passevent_v2',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_events_as_actor', to='lineup_app.matchlineup'),
        ),
        migrations.AlterField(
            model_name='passevent_v2',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_events_as_receiver', to='lineup_app.matchlineup'),
        ),
    ]
