# Generated by Django 5.2.1 on 2026-02-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app_v2', '0002_passevent_v2_target_alter_passevent_v2_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevent_v2',
            name='action_type',
            field=models.CharField(choices=[('LOW_BALL', 'Low Ball'), ('HIGH_BALL', 'High Ball'), ('GOAL_KICK', 'Goal Kick'), ('CLEARANCE', 'Clearance'), ('CROSS', 'Cross'), ('THROW_IN', 'Throw In'), ('FOULS', 'Fouls'), ('DRIBBLE', 'Dribble'), ('BALL_SHIELDING', 'Ball Shielding')], max_length=30),
        ),
    ]
