# Generated by Django 5.2.1 on 2026-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app_v2', '0003_alter_passevent_v2_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='passevent_v2',
            name='foul_outcome',
            field=models.CharField(blank=True, choices=[('NO CARD', 'No card'), ('YELLOW CARD', 'Yellow card'), ('RED CARD', 'Red card')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='passevent_v2',
            name='action_type',
            field=models.CharField(choices=[('LOW_BALL', 'Low Ball'), ('HIGH_BALL', 'High Ball'), ('GOAL_KICK', 'Goal Kick'), ('CLEARANCE', 'Clearance'), ('CROSS', 'Cross'), ('THROW_IN', 'Throw In'), ('FOULS', 'Fouls'), ('DRIBBLE', 'Dribble'), ('BALL_SHIELDING', 'Ball Shielding'), ('OFFSIDE', 'Offside')], max_length=30),
        ),
    ]
