# Generated by Django 5.2.1 on 2025-10-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_app', '0001_initial'),
        ('matches_app', '0004_match_opponent_red_cards_match_opponent_yellow_cards'),
        ('players_app', '0002_alter_player_position'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchlineup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches_app.match'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='minutes_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players_app.player'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='pod_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams_app.team'),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='time_in',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchlineup',
            name='time_out',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='matchlineup',
            constraint=models.UniqueConstraint(fields=('match', 'team', 'player'), name='unique_lineup_per_team'),
        ),
    ]
