# Generated by Django 5.2.1 on 2025-10-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_app', '0003_matchlineup_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineup',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('LCB', 'Left Center Back'), ('RCB', 'Right Center Back'), ('RB', 'Right Back'), ('LM', 'Left Midfielder'), ('LCM', 'Left Central Midfielder'), ('RCM', 'Right Central Midfielder'), ('RM', 'Right Midfielder'), ('ST1', 'Striker 1'), ('ST2', 'Striker 2'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CM', 'Central Midfielder'), ('CB', 'Center Back'), ('SUB', 'Substitute')], default='SUB', max_length=5, null=True),
        ),
    ]
