# Generated by Django 5.2.12 on 2026-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_app', '0004_alter_matchlineup_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='is_unused_sub',
            field=models.BooleanField(default=False),
        ),
    ]
