# Generated by Django 5.2.12 on 2026-05-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging_app', '0008_alter_attempttogoal_outcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagging_app.attempttogoal')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='library_app.highlight')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='reels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.highlight')),
            ],
        ),
    ]
