# Generated by Django 5.2.1 on 2025-08-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches_app', '0001_initial'),
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDefensiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerial_duel_won', models.PositiveIntegerField(default=0)),
                ('aerial_duel_lost', models.PositiveIntegerField(default=0)),
                ('tackle_won', models.PositiveIntegerField(default=0)),
                ('tackle_lost', models.PositiveIntegerField(default=0)),
                ('physical_duel_won', models.PositiveIntegerField(default=0)),
                ('physical_duel_lost', models.PositiveIntegerField(default=0)),
                ('duel_1v1_won_att', models.PositiveIntegerField(default=0)),
                ('duel_1v1_lost_att', models.PositiveIntegerField(default=0)),
                ('duel_1v1_won_def', models.PositiveIntegerField(default=0)),
                ('duel_1v1_lost_def', models.PositiveIntegerField(default=0)),
                ('foul_committed', models.PositiveIntegerField(default=0)),
                ('foul_won', models.PositiveIntegerField(default=0)),
                ('corner', models.PositiveIntegerField(default=0)),
                ('offside', models.PositiveIntegerField(default=0)),
                ('yellow_card', models.PositiveIntegerField(default=0)),
                ('red_card', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
        ),
    ]
