# Generated by Django 5.2.1 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdefensivestats',
            name='defensive_line_breaks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerdefensivestats',
            name='line_breaks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
