# Generated by Django 5.2.1 on 2025-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdefensivestats',
            name='corner',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
