# Generated by Django 5.2.1 on 2025-09-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_app', '0002_auto_20250913_1658'),
        ('defensive_app', '0002_playerdefensivestats_corner'),
    ]

    operations = [
    ]
