# Generated by Django 5.2.1 on 2025-09-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_app', '0002_playerdefensivestats_defensive_line_breaks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdefensivestats',
            name='corner',
        ),
    ]
