# Generated by Django 5.2.1 on 2025-09-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defensive_app', '0003_merge_20250915_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdefensivestats',
            name='corner',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
