# Generated by Django 5.2.1 on 2025-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age_group',
            field=models.CharField(choices=[('U20', 'Under 20'), ('U17', 'Under 17'), ('U15', 'Under 15')], default='U20', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='foot_preference',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Right', max_length=5),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=0, default=170, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='files_to_be_imported/default_image.png', upload_to='player_photos/'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=65, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Forward', 'Forward'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], max_length=50),
        ),
    ]
