# Generated by Django 5.2.1 on 2025-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_player_age_group_player_foot_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default=0.9995061728395062, max_length=20),
            preserve_default=False,
        ),
    ]
