# Generated by Django 5.2.1 on 2025-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_match_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League')], default='Local Friendly', max_length=50),
        ),
    ]
