# Generated by Django 5.2.1 on 2025-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0003_player_jina_maarufu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='jina_maarufu',
            field=models.CharField(blank=True, default='nickname', max_length=50, null=True),
        ),
    ]
