# Generated by Django 5.2.1 on 2025-11-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0005_player_joined_azamfc_year_player_medical_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='joined_azamfc_year',
            new_name='joined_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight',
        ),
        migrations.AddField(
            model_name='player',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PlayerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, default=170, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=65, max_digits=5)),
                ('date_measured', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='players_app.player')),
            ],
            options={
                'ordering': ['-date_measured'],
            },
        ),
    ]
