# Generated by Django 5.2.12 on 2026-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0008_alter_player_leve_of_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'Signed'), ('TRIAL', 'Trial')], default='SIGNED', max_length=10),
        ),
    ]
