# Generated by Django 5.2.12 on 2026-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0009_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('SIGNED', 'Signed'), ('TRIAL', 'Trial'), ('LOANED', 'Loaned')], default='SIGNED', max_length=10),
        ),
    ]
