# Generated by Django 5.2.12 on 2026-04-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams_app', '0004_alter_staffmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('role', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('FB', 'Full Back'), ('WB', 'Wing Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('WM', 'Wide Midfielder'), ('W', 'Winger'), ('ST', 'Striker')], max_length=10)),
                ('preferred_foot', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=10)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loaned_players/photos/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('loan_club_region', models.CharField(help_text='Region where the loan club is located', max_length=100)),
                ('loan_club_country', models.CharField(help_text='Country where the loan club is located', max_length=100)),
                ('loan_start_date', models.DateField()),
                ('loan_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_players', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('training', 'Training'), ('match', 'Match')], max_length=10)),
                ('training_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_type', models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly'), ('international', 'International'), ('Tournament', 'Tournament')], max_length=20, null=True)),
                ('competition_name', models.CharField(blank=True, choices=[('NBC Premier League', 'NBC Premier League'), ('first_league', 'First League'), ('NMB Mapinduzi Cup', 'NMB Mapinduzi Cup'), ('CRDB Federation Cup', 'CRDB Federation Cup'), ('CAF Confederation Cup', 'CAF Confederation Cup'), ('International Friendly', 'International Friendly'), ('Local Friendly', 'Local Friendly')], max_length=50, null=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team_side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True)),
                ('appearance', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('minutes_played', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_in', models.BooleanField(default=False)),
                ('sub_in_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_out', models.BooleanField(default=False)),
                ('sub_out_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('pre_assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_away_matches', to='teams_app.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_home_matches', to='teams_app.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='loans_app.loanedplayer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
