# Generated by Django 5.2.12 on 2026-04-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandailyentry',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='loandailyentry',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='loandailyentry',
            name='result',
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='away_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='competition_name',
            field=models.CharField(blank=True, choices=[('NBC Premier League', 'NBC Premier League'), ('first_league', 'First League'), ('NMB Mapinduzi Cup', 'NMB Mapinduzi Cup'), ('CRDB Federation Cup', 'CRDB Federation Cup'), ('CAF Confederation Cup', 'CAF Confederation Cup'), ('International Friendly', 'International Friendly'), ('Local Friendly', 'Local Friendly')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='competition_type',
            field=models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly'), ('international', 'International'), ('Tournament', 'Tournament')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='home_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loandailyentry',
            name='team_side',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True),
        ),
    ]
