# Generated by Django 5.2.1 on 2025-08-14 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', models.DateField()),
                ('title', models.CharField(default='Plan for Tomorrow', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams_app.agegroup')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('activity', models.CharField(max_length=200)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='announcements_app.announcement')),
            ],
        ),
    ]
