"""
Django settings for player_statistics_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d6-hxwo53dojql00)t==rs-ftwko*e_ap(7cd(&nt&uq@6@ofl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local
    'version1.accounts_app', 'version1.players_app',  'version1.matches_app', 'version1.actions_app',
    'version1.gps_app', 'version1.teams_app.apps.TeamsAppConfig', 'version1.announcements_app',  'version1.reports_app',
    'version1.tagging_app', 'version1.goalkeeping_app', 'version1.defensive_app', 'version1.lineup_app',
    'version1.perfomance_rating_app', 'version1.training_app', 'version1.sheets_generator_app',

    #loaned_players
    'version1.loans_app',

    # Third party
     'rest_framework',

    ##version2
     'version2.tagging_app_v2',
     'version2.reports_app_v2',

    # version3
    'version3.tagging_app_v3',
     
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'player_statistics_project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'version1.players_app.context_processors.player_filters',
                'version1.teams_app.context_processors.our_teams_context',

                # Add this line
                'django.template.context_processors.debug',

                # local
                "version1.matches_app.context_processors.competitions_processor",

            ],
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]


WSGI_APPLICATION = 'player_statistics_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATIC FILES
STATIC_URL = '/static_player_statistics2/'
STATIC_ROOT = '/home/afcportal/public_html/static_player_statistics2'

STATICFILES_DIRS = [

    #version1 (FIXED PATHS)
    os.path.join(BASE_DIR, 'version1', 'accounts_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'actions_app', 'static'),
    #os.path.join(BASE_DIR, 'version1', 'announcement_app', 'static'),
    #os.path.join(BASE_DIR, 'version1', 'defensive_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'goalkeeping_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'gps_app', 'static'),
    #os.path.join(BASE_DIR, 'version1', 'lineup_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'matches_app', 'static'),
    #os.path.join(BASE_DIR, 'version1', 'perfomance_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'players_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'reports_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'tagging_app', 'static'),
    os.path.join(BASE_DIR, 'version1', 'teams_app', 'static'),
    #os.path.join(BASE_DIR, 'version1', 'training_app', 'static'),

    os.path.join(BASE_DIR, 'static'),  # optional: for global/static files

    #version2 (FIXED PATH)
    #os.path.join(BASE_DIR, 'version2', 'tagging_app_v2', 'static'),

    #version3
]

# MEDIA FILES
MEDIA_URL = '/media_player_statistics2/'
MEDIA_ROOT = '/home/afcportal/public_html/media_player_statistics2'

#MEDIA_URL = '/media/'
#MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = 'home'  # redirect after login
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'accounts_app:login'


TIME_INPUT_FORMATS = ['%H:%M']


# Development (prints emails in console)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Real email via Gmail SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.azamfcportal.com"
EMAIL_PORT =  465 # or 587 depending on your server
EMAIL_USE_SSL = True # for ort 465
#EMAIL_USE_TLS = True # for port 587
EMAIL_HOST_USER = "noreply@azamfcportal.com"  # your Gmail
EMAIL_HOST_PASSWORD = "Nthterm@2019"
DEFAULT_FROM_EMAIL = "Azam FC Portal <noreply@azamfcportal.com>"