# Generated by Django 5.2.1 on 2025-07-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches_app', '0001_initial'),
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerActionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_passes', models.PositiveIntegerField(default=0)),
                ('total_passes', models.PositiveIntegerField(default=0)),
                ('crosses', models.PositiveIntegerField(default=0)),
                ('total_crosses', models.PositiveIntegerField(default=0)),
                ('shots_on_target', models.PositiveIntegerField(default=0)),
                ('shots_off_target', models.PositiveIntegerField(default=0)),
                ('blocked_shots', models.PositiveIntegerField(default=0)),
                ('successful_dribbles', models.PositiveIntegerField(default=0)),
                ('total_dribbles', models.PositiveIntegerField(default=0)),
                ('successful_ground_duels', models.PositiveIntegerField(default=0)),
                ('total_ground_duels', models.PositiveIntegerField(default=0)),
                ('clearances', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('fouls_won', models.PositiveIntegerField(default=0)),
                ('successful_take_ons', models.PositiveIntegerField(default=0)),
                ('total_take_ons', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('shots_on_target_faced', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('key_passes', models.PositiveIntegerField(default=0)),
                ('aerial_duels_won', models.PositiveIntegerField(default=0)),
                ('total_aerial_duels', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
    ]
