# Generated by Django 5.2.1 on 2025-07-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerActionStats',
        ),
    ]
