# Generated by Django 5.2.1 on 2025-07-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions_app', '0002_delete_playeractionstats'),
        ('matches_app', '0007_playermatchstats_is_starting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamActionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='e.g. AZAM U20 or Opponent', max_length=100)),
                ('is_our_team', models.BooleanField(default=True)),
                ('shots_on_target_inside_box', models.PositiveIntegerField(default=0)),
                ('shots_on_target_outside_box', models.PositiveIntegerField(default=0)),
                ('shots_off_target_inside_box', models.PositiveIntegerField(default=0)),
                ('shots_off_target_outside_box', models.PositiveIntegerField(default=0)),
                ('blocked_shots', models.PositiveIntegerField(default=0)),
                ('corners', models.PositiveIntegerField(default=0)),
                ('successful_crosses', models.PositiveIntegerField(default=0)),
                ('unsuccessful_crosses', models.PositiveIntegerField(default=0)),
                ('aerial_duel_won', models.PositiveIntegerField(default=0)),
                ('aerial_duel_lost', models.PositiveIntegerField(default=0)),
                ('missed_chances', models.PositiveIntegerField(default=0)),
                ('bad_passes', models.PositiveIntegerField(default=0)),
                ('ball_lost', models.PositiveIntegerField(default=0)),
                ('duel_1v1_won', models.PositiveIntegerField(default=0)),
                ('fouls_committed', models.PositiveIntegerField(default=0)),
                ('fouls_won', models.PositiveIntegerField(default=0)),
                ('mistakes', models.PositiveIntegerField(default=0)),
                ('offsides', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_actions_stats', to='matches_app.match')),
            ],
            options={
                'verbose_name': 'Team Action Stats',
                'verbose_name_plural': 'Team Action Stats',
            },
        ),
    ]
