# Generated by Django 5.2.1 on 2025-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamactionstats',
            name='is_our_team',
            field=models.BooleanField(default=True, help_text='Is this for our team? Yes = Our team, No = Opponent'),
        ),
        migrations.AlterField(
            model_name='teamactionstats',
            name='team_name',
            field=models.CharField(editable=False, help_text='e.g. AZAM U20 or Opponent', max_length=100),
        ),
    ]
