# Generated by Django 5.2.1 on 2025-07-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0004_alter_teamactionstats_is_our_team_and_more'),
        ('matches_app', '0007_playermatchstats_is_starting'),
        ('players_app', '0008_alter_player_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDetailedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_on_target_inside_box', models.PositiveIntegerField(default=0)),
                ('shots_on_target_outside_box', models.PositiveIntegerField(default=0)),
                ('shots_off_target_inside_box', models.PositiveIntegerField(default=0)),
                ('shots_off_target_outside_box', models.PositiveIntegerField(default=0)),
                ('successful_cross', models.PositiveIntegerField(default=0)),
                ('unsuccessful_cross', models.PositiveIntegerField(default=0)),
                ('missed_chance', models.PositiveIntegerField(default=0)),
                ('bad_chance', models.PositiveIntegerField(default=0)),
                ('touches_inside_box', models.PositiveIntegerField(default=0)),
                ('blocked_shots', models.PositiveIntegerField(default=0)),
                ('aerial_duel_won', models.PositiveIntegerField(default=0)),
                ('aerial_duel_lost', models.PositiveIntegerField(default=0)),
                ('one_v_one_duel_won', models.PositiveIntegerField(default=0)),
                ('one_v_one_duel_lost', models.PositiveIntegerField(default=0)),
                ('ball_lost', models.PositiveIntegerField(default=0)),
                ('corners', models.PositiveIntegerField(default=0)),
                ('offsides', models.PositiveIntegerField(default=0)),
                ('fouls_committed', models.PositiveIntegerField(default=0)),
                ('fouls_won', models.PositiveIntegerField(default=0)),
                ('mistakes', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('punches', models.PositiveIntegerField(default=0)),
                ('drops', models.PositiveIntegerField(default=0)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('penalties_saved', models.PositiveIntegerField(default=0)),
                ('is_our_team', models.BooleanField(default=True, help_text='Track only our team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_detailed_actions', to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_actions', to='players_app.player')),
            ],
            options={
                'verbose_name': 'Player Detailed Action',
                'verbose_name_plural': 'Player Detailed Actions',
                'unique_together': {('player', 'match')},
            },
        ),
    ]
