# Generated by Django 5.2.1 on 2025-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0005_playerdetailedaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdetailedaction',
            name='missed_chance',
        ),
        migrations.AddField(
            model_name='playerdetailedaction',
            name='missed_pass',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
