# Generated by Django 5.2.1 on 2025-07-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0006_remove_playerdetailedaction_missed_chance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdetailedaction',
            old_name='bad_chance',
            new_name='bad_pass',
        ),
        migrations.RenameField(
            model_name='playerdetailedaction',
            old_name='missed_pass',
            new_name='missed_chance',
        ),
    ]
