# Generated by Django 5.2.1 on 2025-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0007_rename_bad_chance_playerdetailedaction_bad_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetailedaction',
            name='action_type',
            field=models.CharField(choices=[('offensive', 'Offensive'), ('defensive', 'Defensive'), ('set_piece', 'Set Piece'), ('transition', 'Transition'), ('discipline', 'Discipline'), ('goal_keeping', 'Goal Keeping'), ('general', 'General Game Event')], default='offensive', help_text="Category of the player's actions", max_length=20),
        ),
    ]
