# Generated by Django 5.2.1 on 2025-07-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0008_playerdetailedaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetailedaction',
            name='red_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerdetailedaction',
            name='yellow_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
