# Generated by Django 5.2.1 on 2025-07-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0010_playerdetailedaction_minutes_played'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamActionStats',
        ),
    ]
