# Generated by Django 5.2.1 on 2025-07-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0011_delete_teamactionstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdetailedaction',
            name='bad_pass',
        ),
    ]
