# Generated by Django 5.2.1 on 2025-08-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0012_remove_playerdetailedaction_bad_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerDetailedAction',
        ),
    ]
