# Generated by Django 5.2.1 on 2025-09-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfomance_rating_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancerating',
            name='discipline',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
