# Generated by Django 5.2.1 on 2025-11-16 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0009_region_venue_alter_match_venue'),
        ('perfomance_rating_app', '0002_performancerating_discipline'),
        ('players_app', '0005_player_joined_azamfc_year_player_medical_test_and_more'),
        ('teams_app', '0002_teamseasonmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_tokens', to='matches_app.match')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_tokens', to='teams_app.staffmember')),
            ],
            options={
                'unique_together': {('staff', 'match')},
            },
        ),
        migrations.CreateModel(
            name='StaffPlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_ratings', to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_ratings', to='players_app.player')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='teams_app.staffmember')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('staff', 'player', 'match')},
            },
        ),
    ]
