# Generated by Django 5.2.1 on 2025-11-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_app', '0004_alter_player_jina_maarufu'),
        ('teams_app', '0002_teamseasonmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('focus_area', models.CharField(max_length=100)),
                ('objective', models.TextField()),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Football', 'Football'), ('Physical', 'Physical'), ('Medical', 'Medical'), ('Lifestyle', 'Lifestyle'), ('Mental', 'Mental')], max_length=50)),
                ('responsibility', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('follow_up', models.CharField(blank=True, max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='players_app.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan_team', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('born', models.DateField(blank=True, null=True)),
                ('injury_or_illness', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='players_app.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_team', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pdf', models.FileField(upload_to='mesocycles_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesocycles', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(choices=[('MATCH', 'Match'), ('TRAINING', 'Training')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_team', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Scouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pos', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('agreement', models.CharField(choices=[('TRIAL', 'Trial'), ('SIGNING', 'Signing')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_team', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born', models.DateField(blank=True, null=True)),
                ('played_for', models.CharField(max_length=100)),
                ('activity', models.CharField(choices=[('MATCH', 'Match'), ('TRAINING', 'Training')], max_length=20)),
                ('comments', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_records', to='players_app.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_team', to='teams_app.team')),
            ],
        ),
    ]
