# Generated by Django 5.2.1 on 2025-11-08 15:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0004_alter_player_jina_maarufu'),
        ('reports_app', '0004_remove_result_competition_result_competition_type_and_more'),
        ('teams_app', '0002_teamseasonmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('physical_minutes', models.PositiveIntegerField(default=0)),
                ('tactical_minutes', models.PositiveIntegerField(default=0)),
                ('technical_minutes', models.PositiveIntegerField(default=0)),
                ('recovery_minutes', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_minutes', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTrainingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_minutes', to='players_app.player')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_minutes', to='reports_app.trainingminutes')),
            ],
        ),
    ]
