# Generated by Django 5.2.12 on 2026-07-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0017_alter_fitnessplan_end_date_alter_fitnessplan_pdf_and_more'),
        ('teams_app', '0006_team_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertrainingminutes',
            name='trained_with_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trained_players', to='teams_app.team'),
        ),
        migrations.AddField(
            model_name='trainingminutes',
            name='session',
            field=models.CharField(choices=[('TEAM', 'Team Training'), ('GYM', 'Gym Session'), ('INDIVIDUAL', 'Individual Training')], default='TEAM', max_length=20),
        ),
    ]
