# Generated by Django 5.2.12 on 2026-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0018_playertrainingminutes_trained_with_team_and_more'),
        ('teams_app', '0006_team_team_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingminutes',
            constraint=models.UniqueConstraint(fields=('team', 'date', 'session'), name='unique_training_session_per_team_date_session'),
        ),
    ]
