# Generated by Django 5.2.12 on 2026-07-23 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0019_trainingminutes_unique_training_session_per_team_date_session'),
        ('teams_app', '0006_team_team_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('week', models.PositiveIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
            options={
                'unique_together': {('team', 'season', 'week')},
            },
        ),
        migrations.CreateModel(
            name='TableStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_image', models.ImageField(upload_to='reports/weekly/standings/')),
                ('notes', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='reports_app.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='SquadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('coach_comments', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squad_status', to='reports_app.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='MicrocycleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeted_interventions', models.TextField(blank=True)),
                ('positives', models.TextField(blank=True)),
                ('negatives', models.TextField(blank=True)),
                ('learning_points', models.TextField(blank=True)),
                ('next_microcycle', models.TextField(blank=True)),
                ('player_performance_summary', models.TextField(blank=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='reports_app.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_points', to='reports_app.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField()),
                ('responsible', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_points', to='reports_app.weeklyreport')),
            ],
        ),
    ]
