# Generated by Django 5.2.12 on 2026-07-31 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0020_weeklyreport_tablestanding_squadstatus_and_more'),
        ('teams_app', '0006_team_team_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterActionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned', models.TextField(blank=True, help_text='What was planned for the week?')),
                ('actual', models.TextField(blank=True, help_text='What actually happened?')),
                ('positives', models.TextField(blank=True)),
                ('negatives', models.TextField(blank=True)),
                ('reasons_for_results', models.TextField(blank=True)),
                ('learning_points', models.TextField(blank=True)),
                ('player_performance_summary', models.TextField(blank=True)),
                ('next_microcycle', models.TextField(blank=True)),
                ('coach_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeforeActionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_week_review', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('planned_activities', models.TextField(blank=True)),
                ('expected_challenges', models.TextField(blank=True)),
                ('targeted_interventions', models.TextField(blank=True)),
                ('expected_outcomes', models.TextField(blank=True)),
                ('coach_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='microcycleevaluation',
            name='report',
        ),
        migrations.RemoveField(
            model_name='tablestanding',
            name='report',
        ),
        migrations.AlterModelOptions(
            name='decisionpoint',
            options={'ordering': ['completed', 'deadline']},
        ),
        migrations.AlterModelOptions(
            name='discussionpoint',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'ordering': ['-week_start']},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='decisionpoint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisionpoint',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussionpoint',
            name='category',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('TACTICAL', 'Tactical'), ('PHYSICAL', 'Physical'), ('MEDICAL', 'Medical'), ('PLAYER', 'Player'), ('ADMIN', 'Administrative'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='discussionpoint',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squadstatus',
            name='available_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squadstatus',
            name='new_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squadstatus',
            name='unavailable_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='executive_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='decisionpoint',
            name='responsible',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='squadstatus',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for Revision')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='teams_app.team'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('team', 'season', 'week'), name='unique_weekly_report_per_team_season_week'),
        ),
        migrations.AddField(
            model_name='afteractionreview',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='after_action_review', to='reports_app.weeklyreport'),
        ),
        migrations.AddField(
            model_name='beforeactionreview',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='before_action_review', to='reports_app.weeklyreport'),
        ),
        migrations.DeleteModel(
            name='MicrocycleEvaluation',
        ),
        migrations.DeleteModel(
            name='TableStanding',
        ),
    ]
