# Generated by Django 5.2.12 on 2026-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0021_afteractionreview_beforeactionreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='season',
            field=models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], max_length=20),
        ),
    ]
