# Generated by Django 5.2.12 on 2026-08-26 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0010_alter_player_status'),
        ('reports_app', '0023_alter_result_season_alter_weeklyreport_season'),
        ('teams_app', '0006_team_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerformancePotentialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027')], max_length=20)),
                ('performance', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Average'), (3, '3 - Good')])),
                ('potential', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Average'), (3, '3 - Good')])),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_potential_ratings', to='players_app.player')),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_ratings', to='teams_app.staffmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='teams_app.team')),
            ],
            options={
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['player', '-rated_at'], name='reports_app_player__49e250_idx'), models.Index(fields=['team', 'season', '-rated_at'], name='reports_app_team_id_de4845_idx')],
            },
        ),
    ]
