# Generated by Django 5.2.12 on 2026-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0024_playerperformancepotentialrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingminutes',
            name='session',
            field=models.CharField(choices=[('TEAM', 'Team Training'), ('INDIVIDUAL', 'Individual Training')], default='TEAM', max_length=20),
        ),
    ]
