# Generated by Django 5.2.12 on 2026-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0026_alter_result_competition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertrainingminutes',
            name='participation_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Team'), ('OTHER_TEAM', 'Other Team'), ('NATIONAL_TEAM', 'National Team'), ('INDIVIDUAL', 'Individual Training'), ('INJURED', 'Injured'), ('ABSENT', 'Absent')], default='REGULAR', max_length=20),
        ),
    ]
