# Generated by Django 5.2.1 on 2025-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouting',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scouting',
            name='former_club',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='scouting',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Name of guardian (if parent or coach)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scouting',
            name='parent_or_coach_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scouting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scouting',
            name='school_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scouting',
            name='scouting_location',
            field=models.CharField(blank=True, help_text='Place where the player was scouted', max_length=150, null=True),
        ),
    ]
