# Generated by Django 4.0.6 on 2026-01-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0010_alter_result_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='activity',
            field=models.CharField(choices=[('MATCH', 'Match'), ('TRAINING', 'Training'), ('GYME SESSION', 'Gyme Session'), ('TEAM VIDEO SESSION', 'Team Video Session'), ('INDIVIDUAL VIDEO SESSION', 'Individual Video Session')], max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='competition_type',
            field=models.CharField(choices=[('Local Friendly', 'Local Friendly'), ('International Friendly', 'International Friendly'), ('NBC Youth League', 'NBC Youth League'), ('NBC Premier League', 'NBC Premier League'), ('CAF Confederation Cup', 'CAF Confederation Cup'), ('Azam International Talent Showcase', 'Azam International Talent Showcase'), ('NMB Mapinduzi Cup', 'NMB Mapinduzi Cup')], default='Local Friendly', max_length=50),
        ),
        migrations.AlterField(
            model_name='transition',
            name='activity',
            field=models.CharField(choices=[('MATCH', 'Match'), ('TRAINING', 'Training'), ('GYME SESSION', 'Gyme Session'), ('TEAM VIDEO SESSION', 'Team Video Session'), ('INDIVIDUAL VIDEO SESSION', 'Individual Video Session')], max_length=200),
        ),
    ]
