# Generated by Django 5.2.1 on 2026-01-04 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0011_alter_performance_activity_and_more'),
        ('teams_app', '0004_alter_staffmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessplan',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='focus_area',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='week_number',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='end_date',
            field=models.DateField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='pdf',
            field=models.FileField(blank='True', null='True', upload_to='fitness_plan_pdfs/'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='start_date',
            field=models.DateField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='title',
            field=models.CharField(blank='True', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='team',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to='teams_app.team'),
        ),
    ]
