# Generated by Django 5.2.1 on 2026-02-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0013_alter_result_competition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingminutes',
            name='physical_minutes',
        ),
        migrations.RemoveField(
            model_name='trainingminutes',
            name='recovery_minutes',
        ),
        migrations.RemoveField(
            model_name='trainingminutes',
            name='tactical_minutes',
        ),
        migrations.RemoveField(
            model_name='trainingminutes',
            name='technical_minutes',
        ),
    ]
