# Generated by Django 5.2.1 on 2026-02-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0008_alter_player_leve_of_education'),
        ('reports_app', '0014_remove_trainingminutes_physical_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ABSENT', 'Absent'), ('MEDICAL', 'Medical'), ('TRANSITION', 'Transition')], max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='reports_app.trainingminutes')),
            ],
        ),
    ]
