# Generated by Django 5.2.1 on 2026-02-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0015_trainingabsence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingAbsence',
        ),
    ]
