# Generated by Django 4.2.29 on 2026-03-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0004_alter_staffmember_role'),
        ('players_app', '0008_alter_player_leve_of_education'),
        ('reports_app', '0016_delete_trainingabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='fitness_plan_pdfs/'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to='teams_app.team'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playertrainingminutes',
            unique_together={('training_session', 'player')},
        ),
        migrations.CreateModel(
            name='TrainingAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INJURED', 'Injured'), ('SICK', 'Sick'), ('PERSONAL', 'Personal'), ('UNEXCUSED', 'Unexcused')], max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='reports_app.trainingminutes')),
            ],
            options={
                'unique_together': {('training_session', 'player')},
            },
        ),
    ]
