# Generated by Django 5.2.10 on 2026-01-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('preferred_foot', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=10)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loaned_players/photos/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('loan_club', models.CharField(max_length=100)),
                ('loan_club_region', models.CharField(help_text='Region where the loan club is located', max_length=100)),
                ('loan_club_country', models.CharField(help_text='Country where the loan club is located', max_length=100)),
                ('loan_start_date', models.DateField()),
                ('loan_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('training', 'Training'), ('match', 'Match')], max_length=10)),
                ('training_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('match_type', models.CharField(blank=True, choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly'), ('international', 'International')], max_length=20, null=True)),
                ('opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('appearance', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('minutes_played', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_in', models.BooleanField(default=False)),
                ('sub_in_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_out', models.BooleanField(default=False)),
                ('sub_out_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('pre_assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='loans_app.loanedplayer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
