# Generated by Django 5.2.12 on 2026-04-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineup_app', '0004_alter_matchlineup_position'),
        ('matches_app', '0022_alter_competition_type'),
        ('teams_app', '0005_country_team_country_region_team_region_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('ET1', 'Extra Time 1st Half'), ('ET2', 'Extra Time 2nd Half'), ('PEN', 'Penalty Shootout')], default='1H', max_length=5)),
                ('event_type', models.CharField(choices=[('pass', 'Pass'), ('shot', 'Shot'), ('foul', 'Foul'), ('dribble', 'Dribble'), ('gk_distribution', 'GK Distribution'), ('defensive_action', 'Defensive Action')], max_length=30)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('second', models.PositiveIntegerField(default=0)),
                ('x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('LOW_BALL', 'Low Ball'), ('HIGH_BALL', 'High Ball'), ('GOAL_KICK', 'Goal Kick'), ('CLEARANCE', 'Clearance'), ('CROSS', 'Cross'), ('THROW_IN', 'Throw In'), ('FOULS', 'Fouls'), ('DRIBBLE', 'Dribble'), ('BALL_SHIELDING', 'Ball Shielding'), ('OFFSIDE', 'Offside')], max_length=30, null=True)),
                ('foul_outcome', models.CharField(blank=True, choices=[('NO CARD', 'No card'), ('YELLOW CARD', 'Yellow card'), ('RED CARD', 'Red card')], max_length=30, null=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Cross', 'Cross'), ('Loose Ball', 'Loose Ball'), ('Corner', 'Corner'), ('Free Kick', 'Free Kick'), ('Rebound', 'Rebound')], max_length=20, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error'), ('Own Goal', 'Own Goal'), ('Post', 'Post'), ('Crossbar', 'Crossbar')], max_length=30, null=True)),
                ('body_part', models.CharField(blank=True, choices=[('Right Foot', 'Right Foot'), ('Left Foot', 'Left Foot'), ('Header', 'Header'), ('Other', 'Other')], max_length=20, null=True)),
                ('location_tag', models.CharField(blank=True, choices=[('Outside box left', 'Outside box left'), ('Outside box center', 'Outside box center'), ('Outside box right', 'Outside box right'), ('Inside box left', 'Inside box left'), ('Inside box center', 'Inside box center'), ('Inside box right', 'Inside box right'), ('Six-yard box left', 'Six-yard box left'), ('Six-yard box center', 'Six-yard box center'), ('Six-yard box right', 'Six-yard box right'), ('Penalty spot', 'Penalty spot'), ('Long Range', 'Long Range'), ('Other', 'Other')], max_length=30, null=True)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('video_clip', models.FileField(blank=True, null=True, upload_to='event_clips/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_actor', to='lineup_app.matchlineup')),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='lineup_app.matchlineup')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches_app.match')),
                ('own_goal_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v3_benefited_from_own_goals', to='teams_app.team')),
                ('pre_assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assists', to='lineup_app.matchlineup')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_receiver', to='lineup_app.matchlineup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
    ]
