# Generated by Django 5.2.1 on 2025-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0004_match_opponent_red_cards_match_opponent_yellow_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('AZAM COMPLEX', 'AZAM COMPLEX'), ('NDC STADIUM', 'NDC_STADIUM')], default='AZAM COMPLEX', max_length=50),
        ),
    ]
