# Generated by Django 4.0.6 on 2025-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0006_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('AZAM COMPLEX', 'AZAM COMPLEX'), ('NDC STADIUM', 'NDC STADIUM'), ('MAJALIWA', 'MAJALIWA')], default='AZAM COMPLEX', max_length=50),
        ),
    ]
