# Generated by Django 5.2.1 on 2025-11-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0007_alter_match_competition_type_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('AZAM COMPLEX', 'AZAM COMPLEX'), ('NDC STADIUM', 'NDC STADIUM'), ('MAJALIWA', 'MAJALIWA'), ('MKWAKWANI STADIUM', 'MKWAKWANI STADIUM')], default='AZAM COMPLEX', max_length=50),
        ),
    ]
