# Generated by Django 4.0.6 on 2025-11-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0007_alter_match_competition_type_alter_match_venue'),
        ('matches_app', '0009_alter_match_competition_type'),
    ]

    operations = [
    ]
