# Generated by Django 5.2.1 on 2025-11-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0009_region_venue_alter_match_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rating_links_sent',
            field=models.BooleanField(default=False),
        ),
    ]
