# Generated by Django 4.0.6 on 2025-11-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0008_alter_match_venue'),
        ('matches_app', '0011_alter_match_venue'),
    ]

    operations = [
    ]
