# Generated by Django 5.2.1 on 2025-11-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0010_match_rating_links_sent'),
        ('matches_app', '0014_match_rating_links_sent'),
    ]

    operations = [
    ]
