# Generated by Django 5.2.12 on 2026-05-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0022_alter_competition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_no',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Match number in competition', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.CharField(blank=True, default=None, help_text='Competition round or stage', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, default=None, help_text='Optional group/phase for competition', max_length=50, null=True),
        ),
    ]
