# Generated by Django 5.2.12 on 2026-08-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0023_match_match_no_match_round_alter_match_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=20),
        ),
    ]
