# Generated by Django 5.2.12 on 2026-09-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0024_alter_match_season'),
        ('teams_app', '0006_team_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='matches_app.competition')),
            ],
            options={
                'ordering': ['-season'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='competition_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches_app.competitionseason'),
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('competition_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_teams', to='matches_app.competitionseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='teams_app.team')),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionseason',
            constraint=models.UniqueConstraint(fields=('competition', 'season'), name='unique_competition_season'),
        ),
        migrations.AddConstraint(
            model_name='competitionteam',
            constraint=models.UniqueConstraint(fields=('competition_season', 'team'), name='unique_team_in_competition_season'),
        ),
    ]
