# Generated by Django 5.2.12 on 2026-09-12 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0027_match_away_score_match_home_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionrule',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RenameField(
            model_name='competitionrule',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='competitionrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitionrule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitionrule',
            name='competition_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='matches_app.competitionseason'),
        ),
        migrations.AlterField(
            model_name='competitionrule',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
