# Generated by Django 5.2.1 on 2025-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='second_name',
            field=models.CharField(default='Second_name', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='surname',
            field=models.CharField(default='surname', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
