# Generated by Django 5.1.6 on 2025-06-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='natinality',
            new_name='nationality',
        ),
    ]
