# Generated by Django 5.2.1 on 2025-10-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Forward', 'Forward'), ('Winger', 'Winger'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], max_length=50),
        ),
    ]
