# Generated by Django 5.2.1 on 2025-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0002_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jina_maarufu',
            field=models.CharField(default='nickname', max_length=50),
        ),
    ]
