# Generated by Django 5.2.1 on 2025-07-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0002_rename_natinality_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthdate_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.DateField(blank=True, null=True),
        ),
    ]
