# Generated by Django 5.2.1 on 2025-11-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0004_alter_player_jina_maarufu'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined_azamfc_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='medical_test',
            field=models.CharField(choices=[('DONE', 'DONE'), ('NOT DONE', 'NOT DONE')], default='NOT DONE', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='specific_position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CDM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('CF', 'Centre Forward'), ('ST', 'Striker')], help_text='e.g., CB, RW, LW, CM, etc.', max_length=10, null=True),
        ),
    ]
