# Generated by Django 5.2.1 on 2025-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0005_remove_player_birthdate_str_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
