# Generated by Django 5.2.1 on 2025-11-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0006_rename_joined_azamfc_year_player_joined_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leve_of_education',
            field=models.CharField(blank='True', default='FORM-4', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='real_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
