# Generated by Django 5.2.1 on 2025-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0006_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
