# Generated by Django 5.2.1 on 2025-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0007_alter_player_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_group',
            field=models.CharField(choices=[('U20', 'Under 20'), ('U17', 'Under 17'), ('U15', 'Under 15'), ('U13', 'Under 13')], default='U20', max_length=30),
        ),
    ]
