# Generated by Django 5.2.1 on 2025-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0007_player_leve_of_education_player_real_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='leve_of_education',
            field=models.CharField(blank=True, default='FORM-4', max_length=20, null=True),
        ),
    ]
