# Generated by Django 5.2.1 on 2025-07-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0009_player_former_club_alter_player_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_group',
            field=models.CharField(choices=[('U20', 'Under 20'), ('U17', 'Under 17'), ('U15', 'Under 15'), ('U13', 'Under 13'), ('U10', 'Under 10'), ('ALL', 'All Age Groups')], default='U20', help_text='Select the age group the player belongs to.', max_length=30),
        ),
    ]
