# Generated by Django 5.2.1 on 2025-07-27 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0010_alter_player_age_group'),
        ('teams_app', '0006_agegroup_alter_staffmember_age_group_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams_app.agegroup'),
        ),
    ]
