# Generated by Django 5.2.1 on 2025-07-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0011_alter_player_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birthdate',
        ),
    ]
