# Generated by Django 5.2.1 on 2025-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0012_remove_player_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
