# Generated by Django 5.2.1 on 2025-08-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0014_player_is_active'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams_app.team'),
        ),
    ]
