# Generated by Django 5.2.1 on 2025-10-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0004_alter_player_jina_maarufu'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027')], max_length=20)),
                ('jersey_number', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_memberships', to='teams_app.team')),
            ],
            options={
                'ordering': ['season'],
                'unique_together': {('player', 'team', 'season')},
            },
        ),
    ]
