# Generated by Django 5.2.1 on 2025-12-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0002_teamseasonmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('HEAD_COACH', 'Head Coach'), ('ASSISTANT_COACH', 'Assistant Coach'), ('GOALKEEPER_COACH', 'Goalkeeper Coach'), ('FITNESS_COACH', 'Fitness Coach'), ('PHYSIO', 'Physiotherapist'), ('ANALYST', 'Data Analyst'), ('ANALYST', 'Video Analyst'), ('ANALYST', 'Perfomance Analyst'), ('TEAM_MANAGER', 'Team Manager'), ('PSYCHOLOGIST', 'Psychologist'), ('MEDIA_TEAM', 'Media Team'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
