# Generated by Django 5.2.12 on 2026-07-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0005_country_team_country_region_team_region_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_category',
            field=models.CharField(choices=[('CLUB', 'Club'), ('NATIONAL', 'National Team'), ('SCHOOL', 'School'), ('UNIVERSITY', 'University'), ('ACADEMY', 'Academy'), ('SELECT', 'Select'), ('OTHER', 'Other')], default='CLUB', max_length=20),
        ),
    ]
