# Generated by Django 5.1.6 on 2025-06-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('period_name', models.CharField(max_length=50)),
                ('period_number', models.IntegerField()),
                ('max_acceleration', models.FloatField()),
                ('max_deceleration', models.FloatField()),
                ('acceleration_efforts', models.IntegerField()),
                ('deceleration_efforts', models.IntegerField()),
                ('accel_decel_efforts', models.IntegerField()),
                ('accel_decel_efforts_per_minute', models.FloatField()),
                ('duration', models.CharField(max_length=20)),
                ('distance', models.FloatField()),
                ('player_load', models.FloatField()),
                ('max_velocity', models.FloatField()),
                ('max_vel_percent_max', models.FloatField()),
                ('meterage_per_minute', models.FloatField()),
                ('player_load_per_minute', models.FloatField()),
                ('work_rest_ratio', models.FloatField()),
                ('max_heart_rate', models.IntegerField()),
                ('avg_heart_rate', models.IntegerField()),
                ('max_hr_percent_max', models.FloatField()),
                ('avg_hr_percent_max', models.FloatField()),
                ('hr_exertion', models.FloatField()),
                ('red_zone', models.FloatField()),
                ('hr_band_1_duration', models.CharField(max_length=20)),
                ('hr_band_2_duration', models.CharField(max_length=20)),
                ('hr_band_3_duration', models.CharField(max_length=20)),
                ('hr_band_4_duration', models.CharField(max_length=20)),
                ('hr_band_5_duration', models.CharField(max_length=20)),
                ('hr_band_6_duration', models.CharField(max_length=20)),
                ('energy', models.FloatField()),
                ('high_metabolic_load_distance', models.FloatField()),
                ('standing_distance', models.FloatField()),
                ('walking_distance', models.FloatField()),
                ('jogging_distance', models.FloatField()),
                ('running_distance', models.FloatField()),
                ('hi_distance', models.FloatField()),
                ('sprint_distance', models.FloatField()),
                ('sprint_efforts', models.IntegerField()),
                ('sprint_dist_per_min', models.FloatField()),
                ('high_speed_distance', models.FloatField()),
                ('high_speed_efforts', models.IntegerField()),
                ('high_speed_distance_per_minute', models.FloatField()),
                ('impacts', models.IntegerField()),
                ('athlete_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('game_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('athlete_participation_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('period_tags', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
