# Generated by Django 5.2.1 on 2025-07-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0001_initial'),
        ('matches_app', '0004_playermatchstats_fouls_conceded_and_more'),
        ('players_app', '0007_alter_player_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_number', models.CharField(max_length=20)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('distance', models.FloatField()),
                ('duration', models.CharField(max_length=20)),
                ('top_speed', models.FloatField()),
                ('max_velocity', models.FloatField()),
                ('player_load', models.FloatField()),
                ('sprint_distance', models.FloatField()),
                ('sprint_efforts', models.IntegerField()),
                ('high_speed_distance', models.FloatField()),
                ('high_speed_efforts', models.IntegerField()),
                ('acceleration_efforts', models.IntegerField()),
                ('deceleration_efforts', models.IntegerField()),
                ('max_acceleration', models.FloatField()),
                ('max_deceleration', models.FloatField()),
                ('work_rest_ratio', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('red_zone', models.FloatField(blank=True, null=True)),
                ('standing_distance', models.FloatField(blank=True, null=True)),
                ('walking_distance', models.FloatField(blank=True, null=True)),
                ('jogging_distance', models.FloatField(blank=True, null=True)),
                ('running_distance', models.FloatField(blank=True, null=True)),
                ('sprinting_distance', models.FloatField(blank=True, null=True)),
                ('acceleration_distance', models.FloatField(blank=True, null=True)),
                ('deceleration_distance', models.FloatField(blank=True, null=True)),
                ('explosive_distance', models.FloatField(blank=True, null=True)),
                ('sprint_explosive_distance', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='PodAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_number', models.CharField(max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
            options={
                'unique_together': {('match', 'pod_number')},
            },
        ),
        migrations.DeleteModel(
            name='GPSData',
        ),
    ]
