# Generated by Django 5.2.1 on 2025-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('period_name', models.CharField(choices=[('Session', 'Session'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=50)),
                ('period_number', models.IntegerField(blank=True, null=True)),
                ('max_acceleration', models.FloatField(blank=True, null=True)),
                ('max_deceleration', models.FloatField(blank=True, null=True)),
                ('acceleration_efforts', models.IntegerField(blank=True, null=True)),
                ('deceleration_efforts', models.IntegerField(blank=True, null=True)),
                ('accel_decel_efforts', models.IntegerField(blank=True, null=True)),
                ('accel_decel_efforts_per_minute', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('player_load', models.FloatField(blank=True, null=True)),
                ('max_velocity', models.FloatField(blank=True, null=True)),
                ('max_velocity_percent', models.FloatField(blank=True, null=True)),
                ('meterage_per_minute', models.FloatField(blank=True, null=True)),
                ('player_load_per_minute', models.FloatField(blank=True, null=True)),
                ('work_rest_ratio', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('max_hr_percent', models.FloatField(blank=True, null=True)),
                ('avg_hr_percent', models.FloatField(blank=True, null=True)),
                ('hr_exertion', models.FloatField(blank=True, null=True)),
                ('red_zone', models.FloatField(blank=True, null=True)),
                ('heart_rate_band_1_duration', models.FloatField(blank=True, null=True)),
                ('heart_rate_band_2_duration', models.FloatField(blank=True, null=True)),
                ('heart_rate_band_3_duration', models.FloatField(blank=True, null=True)),
                ('heart_rate_band_4_duration', models.FloatField(blank=True, null=True)),
                ('heart_rate_band_5_duration', models.FloatField(blank=True, null=True)),
                ('heart_rate_band_6_duration', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('high_metabolic_load_distance', models.FloatField(blank=True, null=True)),
                ('standing_distance', models.FloatField(blank=True, null=True)),
                ('walking_distance', models.FloatField(blank=True, null=True)),
                ('jogging_distance', models.FloatField(blank=True, null=True)),
                ('running_distance', models.FloatField(blank=True, null=True)),
                ('hi_distance', models.FloatField(blank=True, null=True)),
                ('sprint_distance', models.FloatField(blank=True, null=True)),
                ('sprint_efforts', models.IntegerField(blank=True, null=True)),
                ('sprint_dist_per_min', models.FloatField(blank=True, null=True)),
                ('high_speed_distance', models.FloatField(blank=True, null=True)),
                ('high_speed_efforts', models.IntegerField(blank=True, null=True)),
                ('high_speed_distance_per_minute', models.FloatField(blank=True, null=True)),
                ('impacts', models.IntegerField(blank=True, null=True)),
                ('athlete_tags', models.TextField(blank=True, null=True)),
                ('activity_tags', models.TextField(blank=True, null=True)),
                ('game_tags', models.TextField(blank=True, null=True)),
                ('athlete_participation_tags', models.TextField(blank=True, null=True)),
                ('period_tags', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_1_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_2_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_3_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_4_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_5_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_6_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='period_name',
            field=models.CharField(blank=True, choices=[('Session', 'Session'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=100, null=True),
        ),
    ]
