# Generated by Django 5.2.1 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsrecord',
            name='heart_rate_band_1_duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='heart_rate_band_2_duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='heart_rate_band_3_duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='heart_rate_band_4_duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='heart_rate_band_5_duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='heart_rate_band_6_duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
