# Generated by Django 5.2.1 on 2025-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0002_gpsrecord_podassignment_delete_gpsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsrecord',
            name='impacts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='meterage_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='player_load_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
