# Generated by Django 5.2.1 on 2025-09-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0002_alter_gpsrecord_heart_rate_band_1_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsrecord',
            name='heart_rate_band_1_duration',
        ),
        migrations.RemoveField(
            model_name='gpsrecord',
            name='heart_rate_band_2_duration',
        ),
        migrations.RemoveField(
            model_name='gpsrecord',
            name='heart_rate_band_3_duration',
        ),
        migrations.RemoveField(
            model_name='gpsrecord',
            name='heart_rate_band_4_duration',
        ),
        migrations.RemoveField(
            model_name='gpsrecord',
            name='heart_rate_band_5_duration',
        ),
        migrations.RemoveField(
            model_name='gpsrecord',
            name='heart_rate_band_6_duration',
        ),
    ]
