# Generated by Django 5.2.1 on 2025-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0003_gpsrecord_impacts_gpsrecord_meterage_per_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsrecord',
            name='top_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
