# Generated by Django 5.2.1 on 2025-08-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0005_remove_gpsrecord_top_speed'),
        ('matches_app', '0016_alter_match_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsrecord',
            name='pod_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.matchlineup'),
        ),
        migrations.DeleteModel(
            name='PodAssignment',
        ),
    ]
