# Generated by Django 5.2.1 on 2025-08-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0006_alter_gpsrecord_pod_number_delete_podassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsrecord',
            old_name='pod_number',
            new_name='lineup',
        ),
    ]
