# Generated by Django 5.2.1 on 2025-08-08 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0007_rename_pod_number_gpsrecord_lineup'),
        ('matches_app', '0017_alter_matchlineup_unique_together_and_more'),
        ('players_app', '0014_player_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsrecord',
            name='lineup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_records', to='matches_app.matchlineup'),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_records', to='matches_app.match'),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_records', to='players_app.player'),
        ),
    ]
