# Generated by Django 5.2.1 on 2025-08-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0008_alter_gpsrecord_lineup_alter_gpsrecord_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsrecord',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
