# Generated by Django 5.2.1 on 2025-08-11 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_app', '0009_alter_gpsrecord_duration'),
        ('matches_app', '0018_alter_matchlineup_match_alter_matchlineup_player_and_more'),
        ('players_app', '0014_player_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpsrecord',
            old_name='acceleration_distance',
            new_name='accel_decel_efforts_per_minute',
        ),
        migrations.RenameField(
            model_name='gpsrecord',
            old_name='deceleration_distance',
            new_name='avg_hr_percent_max',
        ),
        migrations.RenameField(
            model_name='gpsrecord',
            old_name='explosive_distance',
            new_name='energy',
        ),
        migrations.RenameField(
            model_name='gpsrecord',
            old_name='sprint_explosive_distance',
            new_name='heart_rate_band_1_duration',
        ),
        migrations.RenameField(
            model_name='gpsrecord',
            old_name='sprinting_distance',
            new_name='heart_rate_band_2_duration',
        ),
        migrations.RemoveField(
            model_name='gpsrecord',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='accel_decel_efforts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='activity_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='athlete_participation_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='athlete_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='game_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_3_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_4_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_5_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='heart_rate_band_6_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='hi_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='high_metabolic_load_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='high_speed_distance_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='hr_exertion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='max_hr_percent_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='max_vel_percent_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='period_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='period_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='period_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='player_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gpsrecord',
            name='sprint_dist_per_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='acceleration_efforts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='avg_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='deceleration_efforts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='high_speed_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='high_speed_efforts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='lineup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches_app.matchlineup'),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='max_acceleration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='max_deceleration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='max_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='max_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player'),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='player_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='sprint_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpsrecord',
            name='sprint_efforts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
