# Generated by Django 5.2.1 on 2025-07-31 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches_app', '0015_remove_passevent_from_player_and_more'),
        ('players_app', '0014_player_is_active'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptToGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('body_part', models.CharField(choices=[('Left Foot', 'Left Foot'), ('Right Foot', 'Right Foot'), ('Head', 'Head'), ('Other', 'Other')], max_length=20)),
                ('delivery_type', models.CharField(choices=[('Pass', 'Pass'), ('Cross', 'Cross'), ('Loose Ball', 'Loose Ball'), ('Corner', 'Corner')], max_length=20)),
                ('outcome', models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error')], max_length=30)),
                ('x', models.DecimalField(blank=True, decimal_places=2, help_text='X position on pitch (0–100)', max_digits=5, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=2, help_text='Y position on pitch (0–100)', max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='players_app.player')),
                ('pre_assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assists', to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='PassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('x_start', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('y_start', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('x_end', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('y_end', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('is_possession_regained', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='players_app.player')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_from', to='teams_app.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_received', to='players_app.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_to', to='teams_app.team')),
            ],
        ),
    ]
