# Generated by Django 5.2.1 on 2025-08-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttogoal',
            name='is_own_goal',
            field=models.BooleanField(default=False),
        ),
    ]
