# Generated by Django 5.2.1 on 2025-08-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches_app', '0015_remove_passevent_from_player_and_more'),
        ('players_app', '0014_player_is_active'),
        ('tagging_app', '0001_initial'),
        ('teams_app', '0007_alter_team_name_team_unique_team_per_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalkeeperDistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('from_feet', 'From Feet'), ('from_hands', 'From Hands'), ('throw', 'Throw Distribution')], max_length=30)),
                ('detail', models.CharField(choices=[('play_onto', 'Play Onto'), ('play_into', 'Play Into'), ('play_around', 'Play Around'), ('play_beyond', 'Play Beyond'), ('other_feet', 'Other (Feet)'), ('side_kick', 'Side Kick'), ('from_hands', 'From Hands'), ('drop_kick', 'Drop Kick'), ('over_arm', 'Over Arm'), ('under_arm', 'Under Arm'), ('side_arm', 'Side Arm'), ('chest_pass', 'Chest Pass')], max_length=30)),
                ('is_complete', models.BooleanField(default=True)),
                ('is_goal_conceded', models.BooleanField(default=False)),
                ('involvement_duration', models.FloatField(blank=True, help_text='Duration in seconds the goalkeeper had the ball', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goalkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk_distributions', to='players_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
    ]
