# Generated by Django 5.2.1 on 2025-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttogoal',
            name='body_part',
            field=models.CharField(choices=[('Right Foot', 'Right Foot'), ('Left Foot', 'Left Foot'), ('Header', 'Header'), ('Other', 'Other')], default='Right Foot', max_length=20),
        ),
        migrations.AddField(
            model_name='attempttogoal',
            name='location_tag',
            field=models.CharField(choices=[('Outside box left', 'Outside box left'), ('Outside box center', 'Outside box center'), ('Outside box right', 'Outside box right'), ('Inside box left', 'Inside box left'), ('Inside box center', 'Inside box center'), ('Inside box right', 'Inside box right'), ('Six-yard box left', 'Six-yard box left'), ('Six-yard box center', 'Six-yard box center'), ('Six-yard box right', 'Six-yard box right'), ('Penalty spot', 'Penalty spot'), ('Long Range', 'Long Range'), ('Other', 'Other')], default='Long Range', max_length=30),
        ),
    ]
