# Generated by Django 5.2.1 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0002_attempttogoal_is_own_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttogoal',
            name='outcome',
            field=models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error')], max_length=30),
        ),
    ]
