# Generated by Django 5.2.1 on 2025-08-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0002_goalkeeperdistributionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttogoal',
            name='minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='second',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
