# Generated by Django 5.2.1 on 2025-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0003_alter_attempttogoal_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttogoal',
            name='is_opponent',
            field=models.BooleanField(default=False, help_text='Was this attempt by the opponent?'),
        ),
    ]
