# Generated by Django 5.2.1 on 2025-08-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0003_alter_attempttogoal_minute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempttogoal',
            name='body_part',
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='outcome',
            field=models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked')], max_length=30),
        ),
    ]
