# Generated by Django 5.2.1 on 2025-09-02 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0002_player_second_name_player_surname_alter_player_name'),
        ('tagging_app', '0004_attempttogoal_is_opponent'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttogoal',
            name='own_goal_for',
            field=models.ForeignKey(blank=True, help_text='If this is an own goal, which team benefits from it?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_goals', to='teams_app.team'),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='is_opponent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='players_app.player'),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
