# Generated by Django 5.2.12 on 2026-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0005_alter_attempttogoal_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttogoal',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='goal_attempt_thumbnails/'),
        ),
        migrations.AddField(
            model_name='attempttogoal',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to='goal_attempt_clips/'),
        ),
    ]
