# Generated by Django 5.2.1 on 2025-09-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0005_attempttogoal_own_goal_for_and_more'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttogoal',
            name='is_opponent',
            field=models.BooleanField(default=False, help_text='This was attempt made by opponent'),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='is_own_goal',
            field=models.BooleanField(default=False, help_text='Mark if this attempt is an own Goal'),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='outcome',
            field=models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error'), ('Own Goal', 'Own Goal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='own_goal_for',
            field=models.ForeignKey(blank=True, help_text='If this is an own goal, which team benefits from it?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefited_from_own_goals', to='teams_app.team'),
        ),
    ]
