# Generated by Django 5.2.12 on 2026-07-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_app', '0010_alter_player_status'),
        ('teams_app', '0006_team_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_sessions', to='teams_app.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_colour', models.CharField(choices=[('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10)),
                ('players', models.ManyToManyField(blank=True, related_name='gym_groups', to='players_app.player')),
                ('gym_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gym_data.gymsession')),
            ],
            options={
                'ordering': ['group_colour'],
            },
        ),
        migrations.CreateModel(
            name='GroupExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('BACK_SQUAT', 'Back Squat'), ('FRONT_SQUAT', 'Front Squat'), ('DEADLIFT', 'Deadlift'), ('BENCH_PRESS', 'Bench Press'), ('LEG_PRESS', 'Leg Press'), ('LUNGES', 'Lunges'), ('ROMANIAN_DEADLIFT', 'Romanian Deadlift'), ('HIP_THRUST', 'Hip Thrust'), ('CALF_RAISE', 'Calf Raise'), ('PUSH_UP', 'Push-Up'), ('PULL_UP', 'Pull-Up'), ('PLANK', 'Plank')], max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=6)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('gym_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gym_data.gymgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gym_group', 'exercise'), name='unique_exercise_per_gym_group')],
            },
        ),
        migrations.AddConstraint(
            model_name='gymgroup',
            constraint=models.UniqueConstraint(fields=('gym_session', 'group_colour'), name='unique_group_colour_per_gym_session'),
        ),
    ]
