# Generated by Django 5.2.12
from django.db import migrations, models
import django.db.models.deletion


def create_exercises_and_convert_data(apps, schema_editor):
    """
    Create the new ExerciseCategory, Exercise and GymType records,
    then convert old GroupExercise.exercise values into Exercise IDs.
    """

    ExerciseCategory = apps.get_model("gym_data", "ExerciseCategory")
    Exercise = apps.get_model("gym_data", "Exercise")
    GymType = apps.get_model("gym_data", "GymType")
    GroupExercise = apps.get_model("gym_data", "GroupExercise")

    # ---------------------------------------------------------
    # 1. Create exercise categories
    # ---------------------------------------------------------

    strength, _ = ExerciseCategory.objects.get_or_create(
        name="Strength"
    )

    core, _ = ExerciseCategory.objects.get_or_create(
        name="Core"
    )

    # ---------------------------------------------------------
    # 2. Create Gym Types
    # ---------------------------------------------------------

    for gym_type_name in [
        "Blue",
        "Yellow",
        "Red",
        "Individual",
        "Rehabilitation",
    ]:
        GymType.objects.get_or_create(name=gym_type_name)

    # ---------------------------------------------------------
    # 3. Create exercises
    # ---------------------------------------------------------

    exercises = {
        "BACK_SQUAT": ("Back Squat", strength),
        "FRONT_SQUAT": ("Front Squat", strength),
        "DEADLIFT": ("Deadlift", strength),
        "BENCH_PRESS": ("Bench Press", strength),
        "LEG_PRESS": ("Leg Press", strength),
        "LUNGES": ("Lunges", strength),
        "ROMANIAN_DEADLIFT": ("Romanian Deadlift", strength),
        "HIP_THRUST": ("Hip Thrust", strength),
        "CALF_RAISE": ("Calf Raise", strength),
        "PUSH_UP": ("Push-Up", strength),
        "PULL_UP": ("Pull-Up", strength),
        "PLANK": ("Plank", core),
    }

    exercise_objects = {}

    for code, (name, category) in exercises.items():

        exercise, _ = Exercise.objects.get_or_create(
            name=name,
            defaults={
                "category_id": category.id,
            },
        )

        exercise_objects[code] = exercise

    # ---------------------------------------------------------
    # 4. IMPORTANT:
    # Convert old exercise values to Exercise IDs
    #
    # At this point the database column is still the old
    # VARCHAR field, so we can safely read values such as
    # "BACK_SQUAT".
    # ---------------------------------------------------------

    for group_exercise in GroupExercise.objects.all():

        old_value = group_exercise.exercise

        if old_value in exercise_objects:

            exercise = exercise_objects[old_value]

            # Temporarily store the new Exercise ID.
            #
            # The actual database column is still a VARCHAR
            # at this point, so this is not yet the final FK.
            group_exercise.exercise = str(exercise.id)
            group_exercise.save(update_fields=["exercise"])

        else:
            raise ValueError(
                f"Unknown old exercise value: {old_value}"
            )


def reverse_conversion(apps, schema_editor):
    """
    Reverse the conversion:
    Exercise ID → old exercise code.
    """

    Exercise = apps.get_model("gym_data", "Exercise")
    GroupExercise = apps.get_model("gym_data", "GroupExercise")

    reverse_mapping = {
        "Back Squat": "BACK_SQUAT",
        "Front Squat": "FRONT_SQUAT",
        "Deadlift": "DEADLIFT",
        "Bench Press": "BENCH_PRESS",
        "Leg Press": "LEG_PRESS",
        "Lunges": "LUNGES",
        "Romanian Deadlift": "ROMANIAN_DEADLIFT",
        "Hip Thrust": "HIP_THRUST",
        "Calf Raise": "CALF_RAISE",
        "Push-Up": "PUSH_UP",
        "Pull-Up": "PULL_UP",
        "Plank": "PLANK",
    }

    for group_exercise in GroupExercise.objects.all():

        try:
            exercise = Exercise.objects.get(
                id=group_exercise.exercise
            )

            group_exercise.exercise = reverse_mapping.get(
                exercise.name,
                exercise.name.upper().replace(" ", "_"),
            )

            group_exercise.save(update_fields=["exercise"])

        except Exercise.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("gym_data", "0001_initial"),
        ("players_app", "0010_alter_player_status"),
    ]

    operations = [

        # -----------------------------------------------------
        # Create ExerciseCategory
        # -----------------------------------------------------

        migrations.CreateModel(
            name="ExerciseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        # -----------------------------------------------------
        # Create Exercise WITHOUT category first
        # -----------------------------------------------------

        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),

        # -----------------------------------------------------
        # Add category to Exercise
        # -----------------------------------------------------

        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exercises",
                to="gym_data.exercisecategory",
                null=True,
            ),
        ),

        # -----------------------------------------------------
        # Create GymType
        # -----------------------------------------------------

        migrations.CreateModel(
            name="GymType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Individual",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        # -----------------------------------------------------
        # Create initial new data and convert old exercise data
        # -----------------------------------------------------

        migrations.RunPython(
            create_exercises_and_convert_data,
            reverse_conversion,
        ),

        # -----------------------------------------------------
        # Now convert GroupExercise.exercise from CharField
        # to ForeignKey
        # -----------------------------------------------------

        migrations.AlterField(
            model_name="groupexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_exercises",
                to="gym_data.exercise",
            ),
        ),

        # -----------------------------------------------------
        # GymGroup changes
        # -----------------------------------------------------

        migrations.AlterModelOptions(
            name="gymgroup",
            options={
                "ordering": ["gym_type__name"],
            },
        ),

        migrations.RemoveConstraint(
            model_name="gymgroup",
            name="unique_group_colour_per_gym_session",
        ),

        migrations.RemoveField(
            model_name="gymgroup",
            name="group_colour",
        ),

        migrations.AddField(
            model_name="gymgroup",
            name="gym_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gym_groups",
                to="gym_data.gymtype",
            ),
        ),

        migrations.AddConstraint(
            model_name="gymgroup",
            constraint=models.UniqueConstraint(
                fields=("gym_session", "gym_type"),
                name="unique_gym_type_per_session",
            ),
        ),
    ]