# Generated by Django 5.2.12 on 2026-09-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_data', '0002_exercise_exercisecategory_gymtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='gym_data.exercisecategory'),
            preserve_default=False,
        ),
    ]
