# Generated by Django 4.0.6 on 2025-09-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches_app', '0001_initial'),
        ('players_app', '0001_initial'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('x_start', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('y_start', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('x_end', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('y_end', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('is_possession_regained', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='players_app.player')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_from', to='teams_app.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_received', to='players_app.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_to', to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='GoalkeeperDistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('second', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('from_feet', 'From Feet'), ('from_hands', 'From Hands'), ('throw', 'Throw Distribution')], max_length=30)),
                ('detail', models.CharField(choices=[('play_onto', 'Play Onto'), ('play_into', 'Play Into'), ('play_around', 'Play Around'), ('play_beyond', 'Play Beyond'), ('other_feet', 'Other (Feet)'), ('side_kick', 'Side Kick'), ('from_hands', 'From Hands'), ('drop_kick', 'Drop Kick'), ('over_arm', 'Over Arm'), ('under_arm', 'Under Arm'), ('side_arm', 'Side Arm'), ('chest_pass', 'Chest Pass')], max_length=30)),
                ('is_complete', models.BooleanField(default=True)),
                ('is_goal_conceded', models.BooleanField(default=False)),
                ('involvement_duration', models.FloatField(blank=True, help_text='Duration in seconds the goalkeeper had the ball', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('goalkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk_distributions', to='players_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptToGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('second', models.PositiveIntegerField(default=0)),
                ('delivery_type', models.CharField(choices=[('Pass', 'Pass'), ('Cross', 'Cross'), ('Loose Ball', 'Loose Ball'), ('Corner', 'Corner')], max_length=20)),
                ('outcome', models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error'), ('Own Goal', 'Own Goal')], max_length=30)),
                ('x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_opponent', models.BooleanField(default=False, help_text='This was attempt made by opponent')),
                ('is_own_goal', models.BooleanField(default=False, help_text='Mark if this attempt is an own Goal')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players_app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('own_goal_for', models.ForeignKey(blank=True, help_text='If this is an own goal, which team benefits from it?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefited_from_own_goals', to='teams_app.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='players_app.player')),
                ('pre_assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assists', to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
        ),
    ]
