# Generated by Django 5.2.1 on 2025-10-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0001_initial'),
        ('tagging_app', '0002_attempttogoal_body_part_attempttogoal_location_tag'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passevent',
            name='ball_out_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_who_kick_the_ball_out', to='players_app.player'),
        ),
        migrations.AddField(
            model_name='passevent',
            name='is_ball_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passevent',
            name='throw_in_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_who_make_a_throw_in', to='players_app.player'),
        ),
        migrations.AddField(
            model_name='passevent',
            name='throw_in_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams_app.team'),
        ),
    ]
