# Generated by Django 5.2.1 on 2025-10-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0001_initial'),
        ('tagging_app', '0003_passevent_ball_out_by_passevent_is_ball_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevent',
            name='from_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passes_made', to='players_app.player'),
        ),
    ]
