# Generated by Django 5.2.1 on 2025-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0004_alter_passevent_from_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttogoal',
            name='delivery_type',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Cross', 'Cross'), ('Loose Ball', 'Loose Ball'), ('Corner', 'Corner'), ('Free kick', 'Free kick')], max_length=20),
        ),
    ]
