# Generated by Django 5.2.11 on 2026-04-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0006_attempttogoal_thumbnail_attempttogoal_video_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempttogoal',
            name='period',
            field=models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('ET1', 'Extra Time 1st Half'), ('ET2', 'Extra Time 2nd Half')], default='1H', max_length=4),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='outcome',
            field=models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('Goal', 'Goal'), ('Blocked', 'Blocked'), ('Error', 'Error'), ('Own Goal', 'Own Goal')], max_length=30),
        ),
    ]
