# Generated by Django 5.2.12 on 2026-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging_app', '0007_attempttogoal_period_alter_attempttogoal_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttogoal',
            name='outcome',
            field=models.CharField(choices=[('Off Target', 'Off Target'), ('On Target Saved', 'On Target Saved'), ('On Target Goal', 'On Target Goal'), ('Blocked', 'Blocked'), ('Player Error', 'Player Error'), ('Own Goal', 'Own Goal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='attempttogoal',
            name='period',
            field=models.CharField(choices=[('1H', 'First Half'), ('2H', 'Second Half'), ('ET1', 'Extra Time First Half'), ('ET2', 'Extra Time Second Half'), ('P', 'Penalty shootout')], default='1H', max_length=5),
        ),
    ]
