# Generated by Django 5.2.12 on 2026-04-14 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(unique=True)),
                ('player_name', models.CharField(max_length=255)),
                ('join_date', models.DateField()),
                ('core_character', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task', models.CharField(choices=[('Insertion', 'Insertion'), ('Observation', 'Observation')], max_length=20)),
                ('iq_range', models.IntegerField(blank=True, null=True)),
                ('cognitive_percent', models.FloatField(blank=True, null=True)),
                ('personality_percent', models.FloatField(blank=True, null=True)),
                ('neuro_psychology_percent', models.FloatField(blank=True, null=True)),
                ('education_percent', models.FloatField(blank=True, null=True)),
                ('overall', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='psychology_app_v2.player')),
            ],
        ),
    ]
