# Generated by Django 5.2.12 on 2026-04-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_app_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('U15', 'U15'), ('U17', 'U17'), ('U20', 'U20'), ('OTHER', 'Other')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychology_app_v2.agegroup'),
        ),
    ]
