# Generated by Django 5.2.12 on 2026-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_app_v2', '0002_agegroup_player_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
