# Generated by Django 5.2.12 on 2026-04-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_app_v2', '0003_alter_player_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id_no',
        ),
    ]
