# Generated by Django 5.2.12 on 2026-08-07 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players_app', '0010_alter_player_status'),
        ('teams_app', '0006_team_team_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visit_type', models.CharField(choices=[('regular_checkup', 'Regular checkup'), ('new_injury', 'New injury')], max_length=30)),
                ('main_complaint', models.CharField(choices=[('knee_pain', 'Knee pain'), ('ankle_pain', 'Ankle pain'), ('groin_pain', 'Groin pain'), ('hamstring_pain', 'Hamstring pain'), ('quadriceps_pain', 'Quadriceps pain'), ('back_pain', 'Back pain'), ('neck_pain', 'Neck pain'), ('finger_pain', 'Finger pain'), ('heel_pain', 'Heel pain'), ('post_operative', 'Post-operative'), ('other', 'Other')], max_length=40)),
                ('body_side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20)),
                ('injury_status', models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('recurrent', 'Recurrent')], default='new', max_length=20)),
                ('mechanism_of_injury', models.CharField(blank=True, choices=[('direct_contact', 'Direct contact'), ('indirect_contact', 'Indirect contact'), ('medical_related', 'Medical related')], max_length=30)),
                ('history_of_injury', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('working_diagnosis', models.TextField(blank=True)),
                ('therapy', models.TextField(blank=True)),
                ('training_session_status', models.CharField(choices=[('full_training', 'Full training'), ('modified_training', 'Modified training'), ('rehabilitation', 'Individual rehabilitation'), ('did_not_train', 'Did not train')], max_length=30)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('restricted', 'Available with restrictions'), ('not_available', 'Not available'), ('reassessment', 'Awaiting reassessment')], default='reassessment', max_length=30)),
                ('recommendations', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_visits', to='players_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_visits', to='teams_app.team')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='medical_data.medicalvisit')),
            ],
            options={
                'ordering': ['review_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('attachment_type', models.CharField(choices=[('mri', 'MRI'), ('xray', 'X-Ray'), ('ultrasound', 'Ultrasound'), ('image', 'Image'), ('video', 'Video'), ('report', 'Medical Report'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_data.medicalvisit')),
            ],
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['date'], name='medical_dat_date_d303f7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['team'], name='medical_dat_team_id_221f66_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['player'], name='medical_dat_player__031038_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['visit_type'], name='medical_dat_visit_t_78de80_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['main_complaint'], name='medical_dat_main_co_46bd67_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalvisit',
            index=models.Index(fields=['availability_status'], name='medical_dat_availab_11588a_idx'),
        ),
    ]
