# Generated by Django 5.2.12 on 2026-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0002_alter_medicalfollowup_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalattachment',
            name='file',
            field=models.FileField(default=1, upload_to='medical_attachments/'),
            preserve_default=False,
        ),
    ]
