# Generated by Django 5.2.12 on 2026-08-27 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0003_medicalattachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('planned_days', models.PositiveIntegerField(help_text='Initial number of recovery days.')),
                ('expected_end_date', models.DateField()),
                ('actual_recovery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('extended', 'Extended')], default='active', max_length=20)),
                ('recovery_notes', models.TextField(blank=True, help_text='General instructions for the recovery period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_recovery_plans', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plan', to='medical_data.medicalvisit')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecoveryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('focus_point', models.CharField(help_text='Main activity or focus for this day.', max_length=250)),
                ('activities', models.TextField(help_text='Detailed activities or instructions for the player.')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('coach_notes', models.TextField(blank=True, help_text='Notes added by the special coach.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='medical_data.medicalrecoveryplan')),
            ],
            options={
                'ordering': ['date', 'day_number'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecoveryplan',
            index=models.Index(fields=['start_date'], name='medical_dat_start_d_e62705_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecoveryplan',
            index=models.Index(fields=['expected_end_date'], name='medical_dat_expecte_d5b495_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecoveryplan',
            index=models.Index(fields=['status'], name='medical_dat_status_0a91e6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecoveryday',
            index=models.Index(fields=['date'], name='medical_dat_date_161c87_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecoveryday',
            index=models.Index(fields=['status'], name='medical_dat_status_83dfb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalrecoveryday',
            constraint=models.UniqueConstraint(fields=('recovery_plan', 'day_number'), name='unique_recovery_plan_day'),
        ),
        migrations.AddConstraint(
            model_name='medicalrecoveryday',
            constraint=models.UniqueConstraint(fields=('recovery_plan', 'date'), name='unique_recovery_plan_date'),
        ),
    ]
