# Generated by Django 5.2.12 on 2026-08-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0004_medicalrecoveryplan_medicalrecoveryday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecoveryplan',
            name='recovery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='main_complaint',
            field=models.CharField(choices=[('knee_pain', 'Knee pain'), ('ankle_pain', 'Ankle pain'), ('groin_pain', 'Groin pain'), ('hamstring_pain', 'Hamstring pain'), ('quadriceps_pain', 'Quadriceps pain'), ('back_pain', 'Back pain'), ('neck_pain', 'Neck pain'), ('finger_pain', 'Finger pain'), ('heel_pain', 'Heel pain'), ('post_operative', 'Post-operative'), ('hip_pain', 'Hip-pain'), ('other', 'Other')], max_length=40),
        ),
    ]
