# Generated by Django 5.2.12 on 2026-08-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0005_alter_medicalrecoveryplan_recovery_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecoveryplan',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
