# Generated by Django 5.2.12 on 2026-09-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_data', '0006_alter_medicalrecoveryplan_expected_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecoveryplan',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecoveryplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('recovered_early', 'Recovered Early'), ('cancelled', 'Cancelled'), ('extended', 'Extended')], default='active', max_length=20),
        ),
    ]
