# Generated by Django 4.0.6 on 2025-09-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineup_app', '0001_initial'),
        ('matches_app', '0001_initial'),
        ('players_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period_name', models.CharField(blank=True, max_length=100, null=True)),
                ('period_number', models.IntegerField(blank=True, null=True)),
                ('max_acceleration', models.FloatField(blank=True, null=True)),
                ('max_deceleration', models.FloatField(blank=True, null=True)),
                ('acceleration_efforts', models.IntegerField(blank=True, null=True)),
                ('deceleration_efforts', models.IntegerField(blank=True, null=True)),
                ('accel_decel_efforts', models.IntegerField(blank=True, null=True)),
                ('accel_decel_efforts_per_minute', models.FloatField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('player_load', models.FloatField(blank=True, null=True)),
                ('max_velocity', models.FloatField(blank=True, null=True)),
                ('max_vel_percent_max', models.FloatField(blank=True, null=True)),
                ('meterage_per_minute', models.FloatField(blank=True, null=True)),
                ('player_load_per_minute', models.FloatField(blank=True, null=True)),
                ('work_rest_ratio', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_hr_percent_max', models.FloatField(blank=True, null=True)),
                ('avg_hr_percent_max', models.FloatField(blank=True, null=True)),
                ('hr_exertion', models.FloatField(blank=True, null=True)),
                ('red_zone', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('high_metabolic_load_distance', models.FloatField(blank=True, null=True)),
                ('standing_distance', models.FloatField(blank=True, null=True)),
                ('walking_distance', models.FloatField(blank=True, null=True)),
                ('jogging_distance', models.FloatField(blank=True, null=True)),
                ('running_distance', models.FloatField(blank=True, null=True)),
                ('hi_distance', models.FloatField(blank=True, null=True)),
                ('sprint_distance', models.FloatField(blank=True, null=True)),
                ('sprint_efforts', models.IntegerField(blank=True, null=True)),
                ('sprint_dist_per_min', models.FloatField(blank=True, null=True)),
                ('high_speed_distance', models.FloatField(blank=True, null=True)),
                ('high_speed_efforts', models.IntegerField(blank=True, null=True)),
                ('high_speed_distance_per_minute', models.FloatField(blank=True, null=True)),
                ('impacts', models.IntegerField(blank=True, null=True)),
                ('athlete_tags', models.TextField(blank=True, null=True)),
                ('activity_tags', models.TextField(blank=True, null=True)),
                ('game_tags', models.TextField(blank=True, null=True)),
                ('athlete_participation_tags', models.TextField(blank=True, null=True)),
                ('period_tags', models.TextField(blank=True, null=True)),
                ('lineup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup_app.matchlineup')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_records', to='matches_app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
            ],
        ),
    ]
