# Generated by Django 5.2.1 on 2026-01-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineup_app', '0004_alter_matchlineup_position'),
        ('matches_app', '0020_remove_match_end_time_remove_match_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassEvent_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SHORT_PASS', 'Short Pass'), ('LONG_PASS', 'Long Pass'), ('GOAL_KICK', 'Goal Kick'), ('CLEARANCE', 'Clearance'), ('CROSS', 'Cross'), ('THROW_IN', 'Throw In'), ('LONG_THROW_IN', 'Long Throw In'), ('DRIBBLE', 'Dribble'), ('BALL_SHIELDING', 'Ball Shielding')], max_length=20)),
                ('timestamp', models.PositiveIntegerField(blank=True, help_text='Match time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_actor', to='lineup_app.matchlineup')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_events_v2', to='matches_app.match')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_receiver', to='lineup_app.matchlineup')),
            ],
            options={
                'ordering': ['timestamp', 'created_at'],
            },
        ),
    ]
