# Generated by Django 5.2.1 on 2025-08-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches_app', '0001_initial'),
        ('players_app', '0001_initial'),
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=False, help_text='True if this player is in the starting eleven')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('RCB', 'Right Center Back'), ('LCB', 'Left Center Back'), ('LB', 'Left Back'), ('RM', 'Right Midfielder'), ('CM', 'Central Midfielder'), ('LM', 'Left Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('ST', 'Striker'), ('SUB', 'Substitute')], default='SUB', max_length=5, null=True)),
                ('pod_number', models.CharField(blank=True, default='Demo', help_text='GPS Pod number assigned to the player in this match', max_length=20, null=True)),
                ('time_in', models.PositiveSmallIntegerField(blank=True, help_text='Minute the player entered the match (e.g. 0 for starting XI or 1). Null = not yet played.', null=True)),
                ('time_out', models.PositiveSmallIntegerField(blank=True, help_text='Minute the player went out of the match. Null = still on pitch or not used.', null=True)),
                ('minutes_played', models.PositiveSmallIntegerField(default=0, help_text='Total minutes this player played in the match; calculated after substitutions or when the match ends.')),
                ('order', models.PositiveSmallIntegerField(blank=True, help_text='Optional ordering key to control display order on UI.', null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, help_text='Match this player is registered for', null=True, on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player', models.ForeignKey(blank=True, help_text='Player registered for this match', null=True, on_delete=django.db.models.deletion.CASCADE, to='players_app.player')),
                ('team', models.ForeignKey(blank=True, help_text='Team this player belongs to (optional if you derive from Player)', null=True, on_delete=django.db.models.deletion.CASCADE, to='teams_app.team')),
            ],
            options={
                'ordering': ['order', 'player__name'],
                'unique_together': {('match', 'player', 'pod_number')},
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(help_text='Minute when the substitution occurred')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(help_text='Match where substitution happened', on_delete=django.db.models.deletion.CASCADE, to='matches_app.match')),
                ('player_in', models.ForeignKey(help_text='Lineup row for the player who came on', on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='lineup_app.matchlineup')),
                ('player_out', models.ForeignKey(help_text='Lineup row for the player who left the pitch', on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to='lineup_app.matchlineup')),
            ],
        ),
    ]
