# Generated by Django 5.2.1 on 2025-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup_app', '0002_alter_matchlineup_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineup',
            name='formation',
            field=models.CharField(blank=True, choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2'), ('3-4-3', '3-4-3'), ('4-5-1', '4-5-1')], max_length=10, null=True),
        ),
    ]
